EXIT_MEANING = {
    0: "SUCCESS",
    1: "UNEXPECTED_ERROR",
    2: "CONFIG_ERROR",
    3: "DATA_ERROR",
    4: "PIPELINE_ERROR",
    5: "SEARCH_ERROR",
    6: "TRAINING_ERROR",
    7: "EVALUATION_ERROR",
    8: "EXPLAINABILITY_ERROR",
    9: "PERSISTENCE_ERROR",
}
