cv: 3

training:
  model:
    learning_rate: 0.03
    depth: 6
    l2_leaf_reg: 3
    random_strength: 1
    border_count: 128
  ensemble:
    bagging_temperature: 1.0
  iterations: 1000

  hardware:
    task_type: CPU

search:
  hardware:
    task_type: GPU
    devices: [0]

# No lineage to avoid Pydantic validation issues. This file is not versioned and is meant to be overridden in most cases by model-specific default configuration files.