name: hotel_management
channels:
  - defaults
dependencies:
  - python=3.11
  - category_encoders
  - numpy
  - joblib
  - pandas
  - scikit-learn
  - xgboost
  - ipykernel
  - pyarrow
  - matplotlib
  - shap
  - seaborn
  - catboost
  - lz4
  - pyyaml
  - pydantic
  - pytest
  - nvidia-ml-py
  - prophet
  - ruff
  - isort
  - mypy
  - pre-commit
  - types-pyyaml
