name: hotel_management
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - category_encoders=2.9.0
  - numpy=1.26.4
  - joblib=1.5.2
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - ipykernel=7.1.0
  - pyarrow=22.0.0
  - matplotlib=3.10.8
  - shap=0.48.0
  - seaborn=0.13.2
  - catboost=1.2.7
  - lz4=4.4.5
  - pyyaml=6.0.3
  - pydantic=2.12.5
  - pytest=9.0.2
  - nvidia-ml-py=13.590.48
  - ruff=0.15.4
  - isort=8.0.1
  - mypy=1.19.1
  - pre-commit=4.5.1
  - types-pyyaml=6.0.12.20250915
  - pytest-cov=7.0.0
  - pdoc=16.0.0