[mypy]
python_version = 3.11
ignore_missing_imports = True
disallow_untyped_defs = False
disallow_any_generics = False
disallow_incomplete_defs = False
disallow_subclassing_any = False
check_untyped_defs = False
warn_unused_ignores = False
warn_return_any = False
strict_optional = False