cancellation_global_v1:
  model_specs: configs/model_specs/cancellation/global/v1.yaml
  runs:
    cancellation_global_v1_run_20260129_163249:
      run_id: cancellation_global_v1_run_20260129_163249
      trained_on: '2026-01-29'
      threshold: 0.51
      artifacts:
        model: ml\artifacts\cancellation\global\v1\cancellation_global_v1_run_20260129_163249\model.joblib
        pipeline: ml\artifacts\cancellation\global\v1\cancellation_global_v1_run_20260129_163249\pipeline.joblib
        metadata: ml\artifacts\cancellation\global\v1\cancellation_global_v1_run_20260129_163249\metadata.json
        metrics: null
        explainability: null
  latest: cancellation_global_v1_run_20260129_163249
  production: null
