name: cancellation
task: binary_classification
version: v1
data:
  features_path: data/features/cancellation/v1/
  target: is_canceled
  train_file: X_train.parquet
  val_file: X_val.parquet
  test_file: X_test.parquet
  y_train: y_train.parquet
  y_val: y_val.parquet
  y_test: y_test.parquet
model:
  class: CatBoostClassifier
  algorithm: catboost
  params:
    random_strength: 4
    min_data_in_leaf: 7
    learning_rate: 0.05
    l2_leaf_reg: 2
    depth: 10
    colsample_bylevel: 1.0
    border_count: 64
    bagging_temperature: 0.75
    iterations: 2500
    task_type: CPU
    random_state: 42
    verbose: 200
  threshold: 0.44
pipeline:
  validate_schema: true
  fill_categorical_missing: true
  feature_engineering: true
  feature_selection: true
explainability:
  feature_importance_method: total_gain
  shap: tree_explainer_mean_abs
