@startuml explain.py Architecture
title explain.py Architecture
left to right direction

skinparam shadowing false
skinparam linetype ortho
skinparam packageStyle rectangle

skinparam package {
    BorderColor black
    BackgroundColor #f0f0f0
    Shadowing false
}

component script as "explain.py"

package "Artifacts" {
    artifact feature_sets_metadata as "Feature Set(s) Metadata\n(feature_store/...)"
    artifact features as "Feature Set(s)\n(feature_store/...)"
    artifact processed_datasets as "Processed Dataset(s)\n(data/processed/...)"
    artifact input_schemas as "Input Schema(s)\n(feature_store/...)"
    artifact derived_schemas as "Derived Schema(s)\n(feature_store/...)\n(optional)"
    artifact training_metadata as "Training Metadata\n(experiments/.../training/...)"
    artifact training_runtime_info as "Training Runtime Info\n(experiments/.../training/...)"
    artifact model as "Trained Model\n(experiments/.../training/...)\n(optional)"
    artifact pipeline as "Trained Pipeline\n(experiments/.../training/...)\n(optional)"
    artifact explainability_metadata as "Explainability Metadata\n(experiments/.../explainability/...)"
    artifact explainability_runtime_info as "Explainability Runtime Info\n(experiments/.../explainability/...)"
    artifact top_k_feature_importances as "Top k Feature Importances\n(experiments/.../explainability/...)\n(optional)"
    artifact top_k_shap_importances as "Top k SHAP Importances\n(experiments/.../explainability/...)\n(optional)"
}

script ..> feature_sets_metadata
script ..> features
script ..> processed_datasets
script ..> input_schemas
script ..> derived_schemas
script ..> model
script ..> pipeline
script ..> training_metadata
script ..> training_runtime_info

script --> explainability_metadata
script --> explainability_runtime_info
script --> top_k_feature_importances
script --> top_k_shap_importances

legend right
..>   Config dependency / read
-->   Create
endlegend

@enduml