@startuml Register Raw Snapshot Architecture
title Register Raw Snapshot Architecture
!include architecture-theme.puml
left to right direction

skinparam shadowing false
skinparam linetype ortho
skinparam packageStyle rectangle

component script as "register_raw_snapshot.py" <<script>>

package "Input Artifacts"<<InputArtifacts>> {
    artifact raw_data as "Raw Data\n(data/raw/...)" <<artifact>>
}

package "Produced Artifacts"<<ProducedArtifacts>> {
    artifact metadata as "Raw Snapshot Metadata\n(data/raw/...)" <<artifact>>
}

script ..> raw_data

script --> metadata

legend right
..>   Config dependency / read
-->   Create
endlegend

@enduml