extends:
  - ../../../../configs/defaults/global.yaml
  - ../../../../configs/defaults/catboost.yaml
  - ../../../../configs/model_specs/special_requests/global/v1.yaml

training:
  iterations: 2500

training_lineage:
  created_by: Sebastijan
  created_at: "2026-02-27T23:53:30Z"