cv: 2

training:
  iterations: 10
  hardware:
    task_type: "cpu"
  snapshot_interval_seconds: 300

search:
  broad:
    iterations: 10
    n_iter: 2
  narrow:
    iterations: 10
    n_iter: 2
  hardware:
    task_type: "gpu"
    devices: [0]
  error_score: "raise"

verbose: 100