problem: cancellation
segment:
  name: global
  description: All bookings
version: v1
task: binary_classification
target: is_canceled
algorithm: catboost
model_class: CatBoostClassifier

pipeline: tabular_catboost_v1

feature_store:
  path: data/feature_store/
  feature_sets:
    - ref: cancellation/global
      name: base_features
      version: v1
      schema_format: csv
      input_schema: input_schema.csv
      derived_schema: derived_schema.csv
      data_format: parquet
      X_train: X_train.parquet
      X_val: X_val.parquet
      X_test: X_test.parquet
      y_train: y_train.parquet
      y_val: y_val.parquet
      y_test: y_test.parquet

data_type: tabular
