name: Run Tests

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-pkgs-
          restore-keys: |
            ${{ runner.os }}-conda-pkgs-

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: hotel_management
          use-mamba: true
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: Show environment
        run: conda run -n hotel_management conda list

      - name: Install coverage
        run: conda run -n hotel_management pip install coverage

      - name: Run tests with coverage
        run: conda run -n hotel_management coverage run -m pytest -v --maxfail=1 --disable-warnings

      - name: Generate coverage xml report
        run: conda run -n hotel_management coverage xml -i

      - name: Show coverage summary
        run: conda run -n hotel_management coverage report -m -i