name: Run Tests

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove existing Conda environment
        run: conda env remove -n hotel_management || true

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-pkgs-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-pkgs-

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: hotel_management
          use-mamba: true
          auto-activate-base: false

      - name: Clear Python caches
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} +
          find . -name "*.pyc" -delete

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Install package in editable mode
        run: conda run -n hotel_management pip install -e .

      - name: Run tests with coverage
        run: conda run -n hotel_management coverage run -m pytest -v --maxfail=1 --disable-warnings